---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: |
            .circleci/greenkeeper
            yarn add -D nyc@11 @oclif/nyc-config@1
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run: yarn test
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  "autodot":
    jobs:
      - node-latest
      - node-8
